[project]
name = "discord-omnis-bot"
version = "0.1.0"
description = "Discord bot Omnis (ORV) - moderation, tickets, logs"
requires-python = ">=3.11"
dependencies = [
  "discord.py==2.4.0",
  "asyncpg==0.29.0",
  "redis[async]==5.0.1",
  "python-dotenv==1.0.1",
  "uvloop==0.19.0"
]

[tool.black]
line-length = 100
